version: 2.0.{build}
image: Ubuntu

build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: Ofb+GjeIm2xiuhm7RXzEpxcFD+UwMMa46S/xg+OOPkyCUgjR+O5K2NeXIXUJnFte
  skip_symbols: true